steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--no-cache', '--rm=true', '-t', 'gcr.io/$PROJECT_ID/server-jre:__VERSION__', '.']

images: ['gcr.io/$PROJECT_ID/server-jre:__VERSION__']
