steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--no-cache', '--rm=true', '--tag', 'gcr.io/$PROJECT_ID/jre', '--tag', 'gcr.io/$PROJECT_ID/jre:8u131', '.']

images: ['gcr.io/$PROJECT_ID/jre']
